### ISSUE TITLE
小声询问，可以linux吗qwq

### ISSUE THREAD

**Issue by NeeeeeeeBs** [avilliai/Petunia#4]
qwq

**Comment by avilliai** [comment]
我不太懂Linux，你可以克隆本项目，然后尝试运行main2.py的源码，我刚刚更新了对应的requirements，python版本需求是3.9

**Comment by NeeeeeeeBs** [comment]
> 我不太懂Linux，你可以克隆本项目，然后尝试运行main2.py的源码，我刚刚更新了对应的requirements，python版本需求是3.9

wqw

**Comment by NeeeeeeeBs** [comment]
悲。。
[root@VM-12-15-centos Petunia-master]# python3 ./main2.py 
2024-05-06 10:29:52,826 - villia - INFO - 欢迎使用
2024-05-06 10:29:52,826 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-06 10:29:52,826 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-06 10:30:02 - ERROR    
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup
    await handler()
  File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

**Comment by avilliai** [comment]
> 悲。。 [root@VM-12-15-centos Petunia-master]# python3 ./main2.py 2024-05-06 10:29:52,826 - villia - INFO - 欢迎使用 2024-05-06 10:29:52,826 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml 2024-05-06 10:29:52,826 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana 2024-05-06 10:30:02 - ERROR Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan async with self.lifespan_context(app) as maybe_state: File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in **aenter** await self._router.startup() File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup await handler() File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup await asyncio.gather(*coros) File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup await self._adapter.login(self.qq) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped return await func(self, *args, **kwargs) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login self.connection = await connect(self.host_name, extra_headers=headers) File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in **await_impl_timeout** return await asyncio.wait_for(self.**await_impl**(), self.open_timeout) File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for raise exceptions.TimeoutError() asyncio.exceptions.TimeoutError

[检查Petunia配置](https://github.com/avilliai/Petunia/issues/2)，确保mirai安装了mirai-api-http并正确配置，同时正常启动，如不可用，**更换至py3.9**。

**Comment by NeeeeeeeBs** [comment]
> > 悲。。 [root@VM-12-15-centos Petunia-master]# python3 ./main2.py 2024-05-06 10:29:52,826 - villia - INFO - 欢迎使用 2024-05-06 10:29:52,826 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml 2024-05-06 10:29:52,826 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana 2024-05-06 10:30:02 - ERROR Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan async with self.lifespan_context(app) as maybe_state: File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in **aenter** await self._router.startup() File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup await handler() File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup await asyncio.gather(*coros) File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup await self._adapter.login(self.qq) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped return await func(self, *args, **kwargs) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login self.connection = await connect(self.host_name, extra_headers=headers) File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in **await_impl_timeout** return await asyncio.wait_for(self.**await_impl**(), self.open_timeout) File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for raise exceptions.TimeoutError() asyncio.exceptions.TimeoutError
> 
> [检查Petunia配置](https://github.com/avilliai/Petunia/issues/2)，确保mirai安装了mirai-api-http并正确配置，同时正常启动，如不可用，**更换至py3.9**。
---------------------------------
### 悲。。这是python3.8运行后的结果
```
[root@VM-12-15-centos Petunia-master]# python3 main2.py 
2024-05-11 10:36:49,359 - villia - INFO - 欢迎使用
2024-05-11 10:36:49,360 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-11 10:36:49,360 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-11 10:36:59 - ERROR    
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup
    await handler()
  File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
----------------------------------------
### 这是Python3.9运行结果
```
```
[root@VM-12-15-centos Petunia-master]# python39 main2.py 
2024-05-11 10:36:42,434 - villia - INFO - 欢迎使用
2024-05-11 10:36:42,434 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-11 10:36:42,434 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-11 10:36:42,557 - villia - ERROR - run() got an unexpected keyword argument 'debug'
```
出错，按任意键退出
```
---------------------------------------------------------------------------------------
### http-api配置如下：
```
adapters: 
  - http
debug: false
enableVerify: true
verifyKey: INITKEYnURKnhyO
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 8081
    cors: [*]
```
-------------------------------------------
```
bot:
  http-api-key: 'INITKEYnURKnhyO'   #mirai-api-http的verify key
  http-api-port: 8081         #mirai-api-http的port
  botqq: xxxx          #机器人的qq
  master: xxxxx           #你的qq
  botName: mika  
```

py38还能跑起来，py39直接报错/哭

**Comment by avilliai** [comment]
> > > 悲。。 [root@VM-12-15-centos Petunia-master]# python3 ./main2.py 2024-05-06 10:29:52,826 - villia - INFO - 欢迎使用 2024-05-06 10:29:52,826 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml 2024-05-06 10:29:52,826 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana 2024-05-06 10:30:02 - ERROR Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan async with self.lifespan_context(app) as maybe_state: File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in **aenter** await self._router.startup() File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup await handler() File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup await asyncio.gather(*coros) File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup await self._adapter.login(self.qq) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped return await func(self, *args, **kwargs) File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login self.connection = await connect(self.host_name, extra_headers=headers) File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in **await_impl_timeout** return await asyncio.wait_for(self.**await_impl**(), self.open_timeout) File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for raise exceptions.TimeoutError() asyncio.exceptions.TimeoutError
> > 
> > 
> > [检查Petunia配置](https://github.com/avilliai/Petunia/issues/2)，确保mirai安装了mirai-api-http并正确配置，同时正常启动，如不可用，**更换至py3.9**。
> 
> ### 悲。。这是python3.8运行后的结果
> ```
> [root@VM-12-15-centos Petunia-master]# python3 main2.py 
> 2024-05-11 10:36:49,359 - villia - INFO - 欢迎使用
> 2024-05-11 10:36:49,360 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
> 2024-05-11 10:36:49,360 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
> 2024-05-11 10:36:59 - ERROR    
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 692, in lifespan
>     async with self.lifespan_context(app) as maybe_state:
>   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 575, in __aenter__
>     await self._router.startup()
>   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 669, in startup
>     await handler()
>   File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 228, in startup
>     await asyncio.gather(*coros)
>   File "/usr/local/lib/python3.8/site-packages/mirai/bot.py", line 137, in startup
>     await self._adapter.login(self.qq)
>   File "/usr/local/lib/python3.8/site-packages/mirai/adapters/base.py", line 35, in wrapped
>     return await func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/mirai/adapters/websocket.py", line 187, in login
>     self.connection = await connect(self.host_name, extra_headers=headers)
>   File "/usr/local/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
>     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
>     raise exceptions.TimeoutError()
> asyncio.exceptions.TimeoutError
> ```
> 
> ### 这是Python3.9运行结果
> [root@VM-12-15-centos Petunia-master]# python39 main2.py 2024-05-11 10:36:42,434 - villia - INFO - 欢迎使用 2024-05-11 10:36:42,434 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml 2024-05-11 10:36:42,434 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana 2024-05-11 10:36:42,557 - villia - ERROR - run() got an unexpected keyword argument 'debug'
> 
> ```
> 出错，按任意键退出
> ```
> 
> ### http-api配置如下：
> ```
> adapters: 
>   - http
> debug: false
> enableVerify: true
> verifyKey: INITKEYnURKnhyO
> singleMode: false
> cacheSize: 4096
> persistenceFactory: 'built-in'
> adapterSettings:
>   ## 详情看 http adapter 使用说明 配置
>   http:
>     host: localhost
>     port: 8081
>     cors: [*]
> ```
> 
> ```
> bot:
>   http-api-key: 'INITKEYnURKnhyO'   #mirai-api-http的verify key
>   http-api-port: 8081         #mirai-api-http的port
>   botqq: xxxx          #机器人的qq
>   master: xxxxx           #你的qq
>   botName: mika  
> ```
> 
> py38还能跑起来，py39直接报错/哭

黄字提示你安装uvicorn和那hyp什么库，你装了是吧，卸了。

**Comment by avilliai** [comment]
黄字一般都是警告信息，你照着它整有时候反而会导致问题。所有需要的依赖都在requirements.txt中列出
pip uninstall uvicorn 
pip uninstall hypercorn
不要听警告信息的额外安装内容，以requirements.txt为准。
![image](https://github.com/avilliai/Petunia/assets/99066610/e685a839-1d69-4a58-84b7-268b2089a011)

**Comment by NeeeeeeeBs** [comment]
```
[root@VM-12-15-centos Petunia-master]# python3 main2.py 
2024-05-11 10:50:46,080 - villia - INFO - 欢迎使用
2024-05-11 10:50:46,080 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-11 10:50:46,081 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-11 10:50:46 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2024-05-11 10:50:56 - ERROR    
2024-05-11 10:50:56,141 - villia - ERROR - 
出错，按任意键退出
[root@VM-12-15-centos Petunia-master]# python39 main2.py 
2024-05-11 10:51:07,438 - villia - INFO - 欢迎使用
2024-05-11 10:51:07,439 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-11 10:51:07,439 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-11 10:51:07 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2024-05-11 10:51:17 - ERROR    
2024-05-11 10:51:17,480 - villia - ERROR - 
出错，按任意键退出
```
现在py38和py39都报错了....
继续悲悲悲==

**Comment by avilliai** [comment]
你的http-api没有配置ws，readme中给出了[http-api配置示例](https://github.com/avilliai/wReply/blob/master/setting.yml)。项目使用的是ws，而非http

**Comment by NeeeeeeeBs** [comment]
```
[root@VM-12-15-centos Petunia-master]# python3 main2.py 
2024-05-11 11:16:46,369 - villia - INFO - 欢迎使用
2024-05-11 11:16:46,369 - villia - INFO - 项目源地址：https://github.com/avilliai/Bergml
2024-05-11 11:16:46,369 - villia - INFO - 此项目拆分自Manyana：https://github.com/avilliai/Manyana
2024-05-11 11:16:46 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2024-05-11 11:16:46 - ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 23456, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 23456)
2024-05-11 11:16:46,400 - villia - ERROR - Multiple exceptions: [Errno 111] Connect call failed ('::1', 23456, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 23456)
出错，按任意键退出
[root@VM-12-15-centos Petunia-master]#
```
这是我http-api设置
```
adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: 1234567890 # 你可以自己设定, 这里作为示范, 请保持和 config.yaml 中 verify_key 项一致
singleMode: false
cacheSize: 4096 # 可选, 缓存大小, 默认4096. 缓存过小会导致引用回复与撤回消息失败
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: localhost
    port: 23457 # 端口
    cors: [*]

  ## 详情看 websocket adapter 使用说明 配置
  ws:
    host: localhost
    port: 23456 # 端口
    reservedSyncId: -1 # 确保为 -1, 否则 WebsocketAdapter(Experimental) 没法正常工作.
```
这是petunia yaml设置
```
bot:
  http-api-key: '1234567890'   #mirai-api-http的verify key
  http-api-port: 23456         #mirai-api-http的port
  botqq: xxxxx             #机器人的qq
  master: xxxx         #你的qq
  botName: mika             #机器人的名字
apiKeys:
```
哭

**Comment by avilliai** [comment]
https://github.com/RockChinQ/QChatGPT/issues/68

https://cloud.tencent.com/developer/ask/sof/290277/answer/449262

**Comment by avilliai** [comment]
相应的，
![image](https://github.com/avilliai/Petunia/assets/99066610/8ffdc9e3-e59e-4f9a-86d2-e5d1fa557c4f)
这里localhost改为对应的ip。

**Comment by NeeeeeeeBs** [comment]
非常感谢，现在已经可以正常运行了！
xd

**Comment by avilliai** [comment]
6H前更新了bing_image_creator.py，即ai绘画的源码文件。同样可根据[issue](https://github.com/avilliai/Petunia/issues/5) 获取cookie，填写bing_dalle3_config.yaml后尝试运行。

**Comment by NeeeeeeeBs** [comment]
好嘞我去pull一下

**Comment by avilliai** [comment]
注意cookie只能在你bot所在设备的浏览器进行获取，否则可能无法使用。
