### ISSUE TITLE
能不能加个死循环，让程序重复执行直到连接成功，不然每次报错都要重新点开程序

### ISSUE THREAD

**Issue by AsleepRay** [avilliai/Petunia#6]

**Comment by avilliai** [comment]
看看报错截图

**Comment by AsleepRay** [comment]
> 看看报错截图

![Image_1717301219777.jpg](https://github.com/avilliai/Petunia/assets/105690722/bf0d569d-dd69-42f3-827c-2241650cd89c)

**Comment by avilliai** [comment]
更新至petunia_v0.6，UI启动已支持自动重连
